# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='公司名称')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '单位表',
                'verbose_name_plural': '单位表',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, null=True, verbose_name='姓')),
                ('last_name', models.CharField(max_length=32, null=True, verbose_name='名')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='地址')),
                ('head_url', models.CharField(max_length=128, null=True, verbose_name='头像')),
                ('create_time', models.TimeField(null=True, verbose_name='创建时间')),
                ('modify_time', models.TimeField(null=True, verbose_name='修改时间')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Company', verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色名称')),
                ('menus', models.ManyToManyField(blank=True, to='crm.Menu')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名称')),
                ('head_url', models.CharField(max_length=128, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='crm.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to='crm.User', verbose_name='修改者'),
        ),
    ]
