# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
    ]
