# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171020_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modify_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify_time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
