# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20171020_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_time2',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
