# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_create_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='create_time2',
        ),
    ]
