# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_customer_create_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modify_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
