# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171020_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='crm.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='url_path',
            field=models.CharField(default=0, max_length=64, verbose_name='链接地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=32, verbose_name='菜单名称'),
        ),
    ]
